export const INSERT_CONTENT = "INSERT_CONTENT";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const DELETE_CONTENT = "DELETE_CONTENT";

export const LOCK_TEMPLATE = "LOCK_TEMPLATE";
export const UNLOCK_TEMPLATE = "UNLOCK_TEMPLATE";
